services:
  - type: web
    name: sage-yaadga
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn dreppnf_platform.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sage-yaadga-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.8"
databases:
  - name: sage-yaadga-db
    databaseName: sage_yaadga
    user: sage_yaadga
