# Generated by Django 5.2.12 on 2026-04-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ceb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.ceb'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrateur'), ('REGIONAL_AGENT', 'Agent regional'), ('PROVINCIAL_USER', 'Utilisateur provincial'), ('PEDAGOGICAL_SUPERVISOR', 'Encadreur pedagogique'), ('SCHOOL_DIRECTOR', "Directeur d'ecole")], default='REGIONAL_AGENT', max_length=32),
        ),
    ]
