# Generated by Django 5.2.12 on 2026-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ceb_user_province_user_region_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrateur'), ('REGIONAL_AGENT', 'Agent régional'), ('PROVINCIAL_USER', 'Utilisateur provincial'), ('PEDAGOGICAL_SUPERVISOR', 'Encadreur pédagogique'), ('SCHOOL_DIRECTOR', "Directeur d'école")], default='REGIONAL_AGENT', max_length=32),
        ),
    ]
