# Generated by Django 5.2.12 on 2026-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_cebevaluation_provinceevaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PUBLIC', 'Publique'), ('PRIVATE', 'Privée'), ('COMMUNITY', 'Communautaire')], default='PUBLIC', max_length=20),
        ),
    ]
