# Generated by Django 5.2.12 on 2026-04-22 09:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('TRADES', 'Metiers scolaires'), ('ICT', 'TIC'), ('ENGLISH', 'Anglais')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('reporting_date', models.DateField(default=django.utils.timezone.now)),
                ('classes_concerned', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('participating_students', models.PositiveIntegerField(default=0)),
                ('trained_teachers', models.PositiveIntegerField(default=0)),
                ('taught_hours', models.PositiveIntegerField(default=0)),
                ('computers_count', models.PositiveIntegerField(default=0)),
                ('has_internet', models.BooleanField(default=False)),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_resources', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.school')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='innovations.innovation')),
            ],
            options={
                'ordering': ['-reporting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('implementation_level', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('student_participation', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observed_results', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='innovations.activity')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='schools.school')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='innovations.innovation')),
            ],
            options={
                'ordering': ['-evaluation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Elevee'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IMPLEMENTED', 'Mise en oeuvre'), ('ARCHIVED', 'Archivee')], default='PENDING', max_length=20)),
                ('generated_by_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_evaluation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_recommendation', to='innovations.evaluation')),
                ('innovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='innovations.innovation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('scope', models.CharField(choices=[('SCHOOL', 'Par ecole'), ('PROVINCE', 'Par province'), ('REGIONAL', 'Regional')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='schools.province')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
