# Generated by Django 5.2.12 on 2026-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0003_activity_updated_at_activitymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='category',
            field=models.CharField(choices=[('TRADES', 'Métiers scolaires'), ('ICT', 'TIC'), ('ENGLISH', 'Anglais')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IMPLEMENTED', 'Mise en œuvre'), ('ARCHIVED', 'Archivée')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='scope',
            field=models.CharField(choices=[('SCHOOL', 'Par école'), ('PROVINCE', 'Par province'), ('REGIONAL', 'Régional')], max_length=20),
        ),
    ]
